[package]
name = "travis-migrate"
version = "1.0.0"
authors = ["Pietro Albini <pietro@pietroalbini.org>"]
edition = "2018"

[dependencies]
failure = "0.1.3"
env_logger = "0.6.0"
log = "0.4.6"
reqwest = "0.9.5"
structopt = "0.2.14"
serde_derive = "1.0.82"
serde = "1.0.82"
